// Generated by gencpp from file my_project_msg/CheckNumberRequest.msg
// DO NOT EDIT!


#ifndef MY_PROJECT_MSG_MESSAGE_CHECKNUMBERREQUEST_H
#define MY_PROJECT_MSG_MESSAGE_CHECKNUMBERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_project_msg
{
template <class ContainerAllocator>
struct CheckNumberRequest_
{
  typedef CheckNumberRequest_<ContainerAllocator> Type;

  CheckNumberRequest_()
    : number(0.0)  {
    }
  CheckNumberRequest_(const ContainerAllocator& _alloc)
    : number(0.0)  {
  (void)_alloc;
    }



   typedef double _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckNumberRequest_

typedef ::my_project_msg::CheckNumberRequest_<std::allocator<void> > CheckNumberRequest;

typedef boost::shared_ptr< ::my_project_msg::CheckNumberRequest > CheckNumberRequestPtr;
typedef boost::shared_ptr< ::my_project_msg::CheckNumberRequest const> CheckNumberRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_project_msg::CheckNumberRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_project_msg::CheckNumberRequest_<ContainerAllocator1> & lhs, const ::my_project_msg::CheckNumberRequest_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_project_msg::CheckNumberRequest_<ContainerAllocator1> & lhs, const ::my_project_msg::CheckNumberRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_project_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dcebbc33e65171f948c63edad2d5dae";
  }

  static const char* value(const ::my_project_msg::CheckNumberRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dcebbc33e65171fULL;
  static const uint64_t static_value2 = 0x948c63edad2d5daeULL;
};

template<class ContainerAllocator>
struct DataType< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_project_msg/CheckNumberRequest";
  }

  static const char* value(const ::my_project_msg::CheckNumberRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 number\n"
"\n"
;
  }

  static const char* value(const ::my_project_msg::CheckNumberRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckNumberRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_project_msg::CheckNumberRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_project_msg::CheckNumberRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<double>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PROJECT_MSG_MESSAGE_CHECKNUMBERREQUEST_H
